[custom]
;不要随意改变关键字，否则会导致出错，注意仔细检查每一行的后面不能有空格，否则可能导致出错
;acl4SSR规则-在线版

;去广告：支持
;自动测速：支持
;微软分流：不支持
;苹果分流：不支持
;增强中国IP段：不支持
;增强国外GFW：不支持
;ruleset=🌋 Paramount,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/ParamountPlus/ParamountPlus.list

ruleset=🛑 全球拦截,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/QuantumultX/Advertising/Advertising.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/chindden/best/main/direct.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list
#ruleset=🌈 Netflix,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Netflix.list
#ruleset=🌈 Netflix,https://raw.githubusercontent.com/chindden/best/main/Netflix.list
#ruleset=🍭 Disney,https://raw.githubusercontent.com/chindden/best/main/DisneyPlus.list
ruleset=🥱 Appletv,https://raw.githubusercontent.com/chindden/best/main/Appletv.list
ruleset=🅰️ AmazonPrime,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/AmazonPrimeVideo/AmazonPrimeVideo.list
ruleset=🌉 BBC,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/BBC/BBC.list
ruleset=✈️ TG,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Telegram.list
ruleset=🧠 OpenAI,https://raw.githubusercontent.com/chindden/best/refs/heads/main/openai.list
ruleset=🧠 Gemini,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Ruleset/AI.list
#ruleset=🗞 AppleNews,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/AppleNews/AppleNews.list
ruleset=🔮 HBO,https://raw.githubusercontent.com/chindden/best/main/hbo.list
#ruleset=🌵 Hulu,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/HuluUSA/HuluUSA.list
#ruleset=🌋 Paramount,https://raw.githubusercontent.com/chindden/best/main/Paramount.list
ruleset=🥱 Fitness,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/FitnessPlus/FitnessPlus.list
#ruleset=🛑 全球拦截,https://raw.githubusercontent.com/privacy-protection-tools/anti-AD/master/anti-ad-clash.yaml
#ruleset=🛑 全球拦截,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list
#ruleset=🛑 全球拦截,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list

#ruleset=🛑 全球拦截,https://raw.githubusercontent.com/DivineEngine/Profiles/master/Surge/Ruleset/Guard/Advertising.list
ruleset=🛑 全球拦截,https://raw.githubusercontent.com/NobyDa/Script/master/Surge/AdRule.list
#ruleset=🛑 全球拦截,https://raw.githubusercontent.com/DivineEngine/Profiles/master/Surge/Ruleset/Guard/Hijacking.list
ruleset=🛑 全球拦截, https://raw.githubusercontent.com/chindden/best/main/myreject.list
ruleset=🐭 卷毛鼠,https://raw.githubusercontent.com/chindden/best/main/JMS.list
ruleset=👽 终点站,https://raw.githubusercontent.com/chindden/best/main/Terminus.list
ruleset=📦 Pikpak,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/PikPak/PikPak.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GoogleCN.list
ruleset=🚀 节点选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Telegram.list
ruleset=🚀 节点选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyMedia.list
ruleset=🚀 节点选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyLite.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
ruleset=🎯 全球直连,[]GEOIP,CN
ruleset=🐟 漏网之鱼,[]FINAL


custom_proxy_group=🚀 节点选择`select`[]♻️ 自动选择`[]DIRECT`.*
custom_proxy_group=♻️ 自动选择`url-test`^(?!.*(国内|中国))`http://www.gstatic.com/generate_204`300,,30
custom_proxy_group=🐮 故障转移`fallback`(BP)`http://www.gstatic.com/generate_204`300,,50
#custom_proxy_group=🌈 Netflix`select`[]🚀 最快的奈飞`.*
#custom_proxy_group=🍭 Disney`select`.*
custom_proxy_group=🔮 HBO`select`.*
#custom_proxy_group=🌵 Hulu`select`(洛杉矶|纽约|US|美国|圣荷西|Oracle|首尔)
#custom_proxy_group=🌋 Paramount`select`(洛杉矶|纽约|US|美国|圣荷西|Oracle|阿姆|迪拜)
custom_proxy_group=🥱 Appletv`select`[]DIRECT`[]🚀 节点选择`[]♻️ 自动选择`.*
custom_proxy_group=🅰️ AmazonPrime`select`[]DIRECT`[]🚀 节点选择`[]♻️ 自动选择`.*
custom_proxy_group=🌉 BBC`select`(伦敦|英国|UK)
custom_proxy_group=🧠 OpenAI`select`.*
custom_proxy_group=✈️ TG`select`[]🐮 故障转移`.*
custom_proxy_group=🧠 Gemini`select`(洛杉矶|纽约|US|美国|圣荷西|Oracle|首尔|BP)
#custom_proxy_group=🗞 AppleNews`select`.*
custom_proxy_group=🥱 Fitness`select`[]DIRECT`[]🐮 故障转移`[]🚀 节点选择`[]♻️ 自动选择
custom_proxy_group=🐭 卷毛鼠`select`[]DIRECT`[]🚀 节点选择`[]♻️ 自动选择`(中国|国内|香港|台湾|新加坡|日本|hk|HK|TW|tw)
custom_proxy_group=👽 终点站`select`[]DIRECT`[]🚀 节点选择`[]♻️ 自动选择`(香港|圣何塞|台湾|日本|新加坡|首尔|hk|HK|TW|tw|CF)
custom_proxy_group=📦 Pikpak`select`[]DIRECT`[]🚀 节点选择`[]♻️ 自动选择`(香港|台湾|日本|新加坡|首尔|hk|HK|TW|tw|CF|SG)
#custom_proxy_group=🚀 最快的奈飞`url-test`(新加坡|香港|台湾|日本|hk|HK|TW|tw)`http://www.gstatic.com/generate_204`300,,20
custom_proxy_group=🎯 全球直连`select`[]DIRECT`[]🚀 节点选择`[]♻️ 自动选择
custom_proxy_group=🛑 全球拦截`select`[]REJECT`[]DIRECT
custom_proxy_group=🐟 漏网之鱼`select`[]🎯 全球直连`[]🚀 节点选择`[]♻️ 自动选择`.*

enable_rule_generator=true
overwrite_original_rules=true
